Let explicit joins precede implicit joins in FROM clause
The SQL standard specifies that explicit joins precede implicit joins. For
example:

```
select * from t1, t2 inner join t1 b on b.x = t2.x
               ^^^   ^^^^^^^^^^
             implicit explicit
              cross    inner
              join     join
```

The second join will be evaluated first. The order of the evaluation is
important for the checking the available fields.

```
-- t1.x is not known to the explicit join
select * from t1, t2 inner join t1 b on b.x=t1.x;
```

In the above case we threw a runtime exception during execution:

```
UnsupportedOperationException: Can't handle Symbol x
```

This now fails in the analyzer with

```
RelationValidationException: missing FROM-clause entry for relation '[doc.t1]'
```